### ISSUE TITLE
Error while copying - HRESULT: 0x800401D0 (CLIPBRD_E_CANT_OPEN)

### ISSUE THREAD

**Issue by ColinDabritz** [ColinDabritz/PoeItemAnalyzer#1]
Logging a bug from dev. I again encountered an exception in the interop/com layer while copying text.

Note the code this was found in will be checked in shortly, with the first refactor extracting the library for clipboard monitoring out.

I had previously copied several times when in background, seemed to work (at least twice).

Note: I had a breakpoint active that logged to the console only (and continued) but this may not matter.

After a delay, I copied another chunk of text from this page out of the chrome browser: https://github.com/Reactive-Extensions/Rx.NET

This is therefore, NOT related to copying quickly, as this was very slow.

I have hit this before, previous comments were:

```
Can apparently throw
System.Runtime.InteropServices.COMException
{"OpenClipboard Failed (Exception from HRESULT: 0x800401D0 (CLIPBRD_E_CANT_OPEN))"}
was copying text real quick. Maybe this is the STA apartment thing?
```

Now the "real quick" factor is no longer relevant.

Transcribed as best I could below.

```
============================
An unhandled exception of type 'System.Runtime.InteropServices.COMException' occurred in PresentationCore.dll

Additional information: OpenClipboard Failed (Exception from HRESULT: 0x800401D0 (CLIPBRD_E_CANT_OPEN))
============================

Details: 

Error code: -2147221040
HelpLink: null
HResult: -2147221040
InnerException: null
Message: OpenClipboard Failed (Exception from HRESULT: 0x800401D0 (CLIPBRD_E_CANT_OPEN))
Source: System

============================
[Larger sections below:]
============================
Data:{System.Collections.ListDictionaryInternal}

Count: 1
IsFixedSize: false
IsReadOnly: false
IsSynchronized: false
Keys: {System.Collections.ListDictionaryInternal.NodeKeyValueCollection}
SyncRoot: {object}
Values: {System.Collections.ListDictionaryInternal.NodeKeyValueCollection}

[Note above is literal, could not expand details further.]

============================

StackTrace: 
   at System.Runtime.InteropServices.ComTypes.IDataObject.GetData(FORMATETC& format, STGMEDIUM& medium)
   at System.Windows.DataObject.OleConverter.GetDataInner(FORMATETC& formatetc, STGMEDIUM& medium)
   at System.Windows.DataObject.OleConverter.GetDataFromOleHGLOBAL(String format, DVASPECT aspect, Int32 index)
   at System.Windows.DataObject.OleConverter.GetDataFromBoundOleDataObject(String format, DVASPECT aspect, Int32 index)
   at System.Windows.DataObject.OleConverter.GetData(String format, Boolean autoConvert, DVASPECT aspect, Int32 index)
   at System.Windows.DataObject.OleConverter.GetData(String format, Boolean autoConvert)
   at System.Windows.DataObject.GetData(String format, Boolean autoConvert)
   at System.Windows.Clipboard.GetDataInternal(String format)
   at System.Windows.Clipboard.GetText(TextDataFormat format)
   at System.Windows.Clipboard.GetText()
   at PoeItemAnalyzer.LogWindow.ClipboardChanged(Object sender, EventArgs e) in C:\Users\Colin\Documents\GitHubVisualStudio\PoeItemAnalyzer\PoeItemAnalyzer\LogWindow.xaml.cs:line 49
   at WpfClipboardMonitor.WindowClipboard.OnClipboardChanged() in C:\Users\Colin\Documents\GitHubVisualStudio\PoeItemAnalyzer\WpfClipboardMonitor\WindowClipboard.cs:line 36
   at WpfClipboardMonitor.WindowClipboard.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled) in C:\Users\Colin\Documents\GitHubVisualStudio\PoeItemAnalyzer\WpfClipboardMonitor\WindowClipboard.cs:line 45
   at System.Windows.Interop.HwndSource.PublicHooksFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at System.Windows.Application.Run()
   at PoeItemAnalyzer.App.Main() in C:\Users\Colin\Documents\GitHubVisualStudio\PoeItemAnalyzer\PoeItemAnalyzer\obj\Debug\App.g.cs:line 0
   at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
   at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
   at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

============================

TargetSite:
{Void GetData(System.Runtime.InteropServices.ComTypes.FORMATETC ByRef, System.Runtime.InteropServices.ComTypes.STGMEDIUM ByRef)}

Attributes: Public | Virtual | HideBySig | NewSlot | Abstract
CallingConvention: Standard | HasThis
ContainsGenericParameters: false
CustomAttributes: Count = 0
DeclaringType: {Name = "IDataObject" FullName = "System.Runtime.InteropServices.ComTypes.IDataObject"}
IsAbstract: true
IsAssembly: false
IsConstructor: false
IsFamily: false
IsFamilyAndAssembly: false
IsFamilyOrAssemly: false
IsFinale: false
IsGenericMethod: false
IsGenericMethodDefinition: false
IsHideBySid: true
IsPrivate: false
IsPublic: true
IsSecurityCrritical: true
IsSecuritySameCritical: true
IsSecurityTransparent: false
IsSpecialName: false
IsStatic: false
IsVirtual: true
MemberType: Method
MetadataToken: 100673570
MethodHandle: {System.RuntimeMethodHandle}
MethodImplementationFlags: IL
Module: System.dll
Name: GetData
ReflectedType: {Name = "IDataObject" FullName = "System.Runtime.InteropServices.ComTypes.IDataObject"}
ReturnParameter: {Void }
ReturnType: {Name = "Void" FullName = "System.Void"}
ReturnTypeCustomAttributes: {Void }

```

**Comment by ColinDabritz** [comment]
This appears to be a known issue with clipboard behavior, only one user at a time: https://stackoverflow.com/questions/68666/clipbrd-e-cant-open-error-when-setting-the-clipboard-from-net
Specifically the citation:
https://msdn.microsoft.com/en-us/library/ms649048(VS.85).aspx
"Opens the clipboard for examination and prevents other applications from modifying the clipboard content."
Opening the clipboard locks it. An error handling loop with repeated reads may be the right answer.

This thread:
https://stackoverflow.com/questions/12769264/openclipboard-failed-when-copy-pasting-data-from-wpf-datagrid
Shows some approaches when handling writing TO the clipboard, including suggesting using `Clipboard.SetDataObject(data)` instead of `Clipboard.SetText(data)`
and one suggestion to use this global (?) error suppression code:

```
void Application_DispatcherUnhandledException(object sender, DispatcherUnhandledExceptionEventArgs e)
{
    var comException = e.Exception as System.Runtime.InteropServices.COMException;

    if (comException != null && comException.ErrorCode == -2147221040)
         e.Handled = true;
}
```

To mitigate, we could delay slightly on first access, or retry in a loop with delay.

**Comment by ColinDabritz** [comment]
I have this reproducing reliably using a second WPF app that pumps clipboard events. It doesn't appear that the other app experiences this error, so it may be that it's my library interaction with the Win32 APIs that is causing further issues, or it could be structural. The key was setting a stream of values on the clipboard rapidly (every 10 ms in this case), and it reproduces within a second on current code.

Test app was added in commit:
https://github.com/ColinDabritz/PoeItemAnalyzer/commit/85bc29e5a93dc8210719eb6d270f17085289c161

Test app alone:

```
Current behaviors (both timers at 10ms):
Only 'Read' checked
No issue, tested >60 seconds

Only 'Read' checked, copying text from other application.
If you spam Ctrl-C elsewhere hard enough (I had text selected in a browser), it will eventually error out in the read with the example error.
took maybe 5-8 seconds of spamming as fast I could (One hand held Ctrl, other spammed C).

Only Send checked
No issue, tested >60 seconds

Only Send checked, copying text from other application (fast spam approach as with read above)
Reproduced the error in about 2 seconds.

Both checked, nothing else
Did reproduce after 10-15 seconds. Apparently an app can also interfer with itself. Delightful.
```

Running both apps:

```
both apps
only read checked, log window open
Lasted some time, ~20-30 seconds?
Error on read with new issue: Exception from HRESULT: 0x800401FD (CO_E_OBJNOTCONNECTED)
Will write up separately.
On second run, 2 minutes, was unable to reproduce
Third run, 5 minutes, no change.

both apps
read checked, log window open
Spamming Ctrl-C in another window
Able to cause error after 10-15 seconds in main app.

both apps
send clipboard
Almost immediate exception on the send side, reproduced 3 times.

Also tested changing to Clipboard.SetDataObject instead of SetText, same issue, might have lasted longer.
```

**Comment by ColinDabritz** [comment]
More info:
Apparently the existing WPF clipboard is handling this similarly with 10 retries, see the reference source code here:

http://referencesource.microsoft.com/#PresentationCore/Core/CSharp/System/Windows/Clipboard.cs,688

See GetDataObjectInternal(), line 688

This uses OLE error checking though.

Note an ExternalException is thrown in some places. Is that our exception type or not?

**Comment by ColinDabritz** [comment]
I added explicit error handling and retry code to address these problems. Long term I'd like to factor out a separate clipboard library that encapsulates this well.
